# Numpy ndarray
numpy ndarrayの基本的な使い方のリスト

In [117]:
import numpy as np

In [118]:
Nx = 3
Ny = 5
Nz = 2
a = np.ones((Nx,Ny,Nz), np.float)

In [119]:
a

array([[[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]]])

In [120]:
a.shape

(3L, 5L, 2L)

In [121]:
a.ndim

3

In [122]:
a.dtype

dtype('float64')

In [123]:
a.size

30

## Other attributs

In [124]:
a.T

array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

In [125]:
a.real

array([[[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]]])

In [126]:
a.imag

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

In [127]:
a.flat

In [128]:
a.ctypes

## Methods

In [129]:
a.tolist()

[[[1.0, 1.0], [1.0, 1.0], [1.0, 1.0], [1.0, 1.0], [1.0, 1.0]],
 [[1.0, 1.0], [1.0, 1.0], [1.0, 1.0], [1.0, 1.0], [1.0, 1.0]],
 [[1.0, 1.0], [1.0, 1.0], [1.0, 1.0], [1.0, 1.0], [1.0, 1.0]]]

In [130]:
a.tostring()

'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?'

In [131]:
a.dumps()

'\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x01cnumpy\nndarray\nq\x02K\x00\x85U\x01b\x87Rq\x03(K\x01\x8a\x01\x03\x8a\x01\x05\x8a\x01\x02\x87cnumpy\ndtype\nq\x04U\x02f8K\x00K\x01\x87Rq\x05(K\x03U\x01<NNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tb\x89U\xf0\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x

### Shpae manipulation

In [132]:
a.shape

(3L, 5L, 2L)

In [133]:
nNx = 2
nNy = (Nx*Ny*Nz)/ nNx
ar = a.reshape((nNx, nNy))
ar.shape

(2L, 15L)

In [134]:
b = a.copy()
b.resize((nNx, nNy))
b.shape

(2L, 15L)

In [135]:
a.shape

(3L, 5L, 2L)

In [136]:
a.transpose().shape

(2L, 5L, 3L)

In [137]:
a.swapaxes(1,2).shape

(3L, 2L, 5L)

In [138]:
# Return a "copy" of the array collapsed into one dimension.
b = a.flatten()
b.shape

(30L,)

In [139]:
# Return a flattened array.
b = a.ravel()
b.shape

(30L,)

In [140]:
a.shape

(3L, 5L, 2L)

In [141]:
a.squeeze([1])

TypeError: an integer is required for the axis

In [142]:
a.squeeze([1,1,1])

TypeError: an integer is required for the axis

## Item selection and manipulation

In [143]:
a.shape

(3L, 5L, 2L)

In [145]:
a.nonzero()

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2], dtype=int64),
 array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 0, 0, 1,
        1, 2, 2, 3, 3, 4, 4], dtype=int64),
 array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
        1, 0, 1, 0, 1, 0, 1], dtype=int64))

In [146]:
a.argmax()

0

In [147]:
a = np.identity(5)

In [148]:
a.argmax()

0

In [149]:
a.argmin()

1

In [150]:
a.min()

0.0

In [151]:
a.max()

1.0

In [153]:
a.ptp()

1.0

In [155]:
a.clip(a.min(), a.max()/2.0)

array([[ 0.5,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0.5,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0.5,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0.5,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0.5]])

In [156]:
a.conj()

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [157]:
a.round()

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [158]:
a.trace()

5.0

In [159]:
a.sum()

5.0

In [160]:
a.cumsum()

array([ 1.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.,  2.,  2.,  3.,
        3.,  3.,  3.,  3.,  3.,  4.,  4.,  4.,  4.,  4.,  4.,  5.])

In [163]:
a.mean(1)

array([ 0.2,  0.2,  0.2,  0.2,  0.2])

In [165]:
a.mean(0)

array([ 0.2,  0.2,  0.2,  0.2,  0.2])

In [166]:
a.var(0)

array([ 0.16,  0.16,  0.16,  0.16,  0.16])

In [167]:
a.std(0)

array([ 0.4,  0.4,  0.4,  0.4,  0.4])

In [170]:
a.prod(1)

array([ 0.,  0.,  0.,  0.,  0.])

In [171]:
a.all()

False

In [172]:
a.any()

True

## Arithmetic and comparison operations

ndarray.__lt__	x.__lt__(y) <==> x<y
ndarray.__le__	x.__le__(y) <==> x<=y
ndarray.__gt__	x.__gt__(y) <==> x>y
ndarray.__ge__	x.__ge__(y) <==> x>=y
ndarray.__eq__	x.__eq__(y) <==> x==y
ndarray.__ne__	x.__ne__(y) <==> x!=y

Truth value of an array (bool):

ndarray.__nonzero__	x.__nonzero__() <==> x != 0
Note
Truth-value testing of an array invokes ndarray.__nonzero__, which raises an error if the number of elements in the the array is larger than 1, because the truth value of such arrays is ambiguous. Use .any() and .all() instead to be clear about what is meant in such cases. (If the number of elements is 0, the array evaluates to False.)

Unary operations:

ndarray.__neg__	x.__neg__() <==> -x
ndarray.__pos__	x.__pos__() <==> +x
ndarray.__abs__() <==> abs(x)	
ndarray.__invert__	x.__invert__() <==> ~x
Arithmetic:

ndarray.__add__	x.__add__(y) <==> x+y
ndarray.__sub__	x.__sub__(y) <==> x-y
ndarray.__mul__	x.__mul__(y) <==> x*y
ndarray.__div__	x.__div__(y) <==> x/y
ndarray.__truediv__	x.__truediv__(y) <==> x/y
ndarray.__floordiv__	x.__floordiv__(y) <==> x//y
ndarray.__mod__	x.__mod__(y) <==> x%y
ndarray.__divmod__(y) <==> divmod(x, y)	
ndarray.__pow__(y[, z]) <==> pow(x, y[, z])	
ndarray.__lshift__	x.__lshift__(y) <==> x<<y
ndarray.__rshift__	x.__rshift__(y) <==> x>>y
ndarray.__and__	x.__and__(y) <==> x&y
ndarray.__or__	x.__or__(y) <==> x|y
ndarray.__xor__	x.__xor__(y) <==> x^y
Note
Any third argument to pow is silently ignored, as the underlying ufunc takes only two arguments.
The three division operators are all defined; div is active by default, truediv is active when __future__ division is in effect.
Because ndarray is a built-in type (written in C), the __r{op}__ special methods are not directly defined.
The functions called to implement many arithmetic special methods for arrays can be modified using set_numeric_ops.
Arithmetic, in-place:

ndarray.__iadd__	x.__iadd__(y) <==> x+=y
ndarray.__isub__	x.__isub__(y) <==> x-=y
ndarray.__imul__	x.__imul__(y) <==> x*=y
ndarray.__idiv__	x.__idiv__(y) <==> x/=y
ndarray.__itruediv__	x.__itruediv__(y) <==> x/y
ndarray.__ifloordiv__	x.__ifloordiv__(y) <==> x//y
ndarray.__imod__	x.__imod__(y) <==> x%=y
ndarray.__ipow__	x.__ipow__(y) <==> x**=y
ndarray.__ilshift__	x.__ilshift__(y) <==> x<<=y
ndarray.__irshift__	x.__irshift__(y) <==> x>>=y
ndarray.__iand__	x.__iand__(y) <==> x&=y
ndarray.__ior__	x.__ior__(y) <==> x|=y
ndarray.__ixor__	x.__ixor__(y) <==> x^=y

## Special methods

For standard library functions:

ndarray.__copy__([order])	Return a copy of the array.
ndarray.__deepcopy__(() -> Deep copy of array.)	Used if copy.deepcopy is called on an array.
ndarray.__reduce__()	For pickling.
ndarray.__setstate__(version, shape, dtype, ...)	For unpickling.
Basic customization:

ndarray.__new__((S, ...)	
ndarray.__array__(...)	Returns either a new reference to self if dtype is not given or a new array of provided data type if dtype is different from the current dtype of the array.
ndarray.__array_wrap__(...)	
Container customization: (see Indexing)

ndarray.__len__() <==> len(x)	
ndarray.__getitem__	x.__getitem__(y) <==> x[y]
ndarray.__setitem__	x.__setitem__(i, y) <==> x[i]=y
ndarray.__getslice__	x.__getslice__(i, j) <==> x[i:j]
ndarray.__setslice__	x.__setslice__(i, j, y) <==> x[i:j]=y
ndarray.__contains__	x.__contains__(y) <==> y in x
Conversion; the operations complex, int, long, float, oct, and hex. They work only on arrays that have one element in them and return the appropriate scalar.

ndarray.__int__() <==> int(x)	
ndarray.__long__() <==> long(x)	
ndarray.__float__() <==> float(x)	
ndarray.__oct__() <==> oct(x)	
ndarray.__hex__() <==> hex(x)	
String representations:

ndarray.__str__() <==> str(x)	
ndarray.__repr__() <==> repr(x)	