In [47]:
import numpy as np

In [48]:
Nx = 3
Ny = 5
Nz = 2
a = np.ones((Nx,Ny,Nz), np.float)

In [49]:
a

array([[[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]]])

In [50]:
a.shape

(3L, 5L, 2L)

In [51]:
a.ndim

3

In [52]:
a.dtype

dtype('float64')

In [53]:
a.size

30

## Other attributs

In [54]:
a.T

array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

In [55]:
a.real

array([[[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]]])

In [56]:
a.imag

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

In [57]:
a.flat

In [58]:
a.ctypes

## Methods

In [59]:
a.tolist()

[[[1.0, 1.0], [1.0, 1.0], [1.0, 1.0], [1.0, 1.0], [1.0, 1.0]],
 [[1.0, 1.0], [1.0, 1.0], [1.0, 1.0], [1.0, 1.0], [1.0, 1.0]],
 [[1.0, 1.0], [1.0, 1.0], [1.0, 1.0], [1.0, 1.0], [1.0, 1.0]]]

In [60]:
a.tostring()

'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?'

In [61]:
a.dumps()

'\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x01cnumpy\nndarray\nq\x02K\x00\x85U\x01b\x87Rq\x03(K\x01\x8a\x01\x03\x8a\x01\x05\x8a\x01\x02\x87cnumpy\ndtype\nq\x04U\x02f8K\x00K\x01\x87Rq\x05(K\x03U\x01<NNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tb\x89U\xf0\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x

### Shpae manipulation

In [62]:
a.shape

(3L, 5L, 2L)

In [63]:
nNx = 2
nNy = (Nx*Ny*Nz)/ nNx
ar = a.reshape((nNx, nNy))
ar.shape

(2L, 15L)

In [64]:
b = a.copy()
b.resize((nNx, nNy))
b.shape

(2L, 15L)

In [65]:
a.shape

(3L, 5L, 2L)

In [67]:
a.transpose().shape

(2L, 5L, 3L)

In [68]:
a.swapaxes(1,2).shape

(3L, 2L, 5L)

In [75]:
# Return a "copy" of the array collapsed into one dimension.
b = a.flatten()
b.shape

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.])

In [74]:
# Return a flattened array.
b = a.ravel()
b.shape

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.])

In [80]:
a.shape

(3L, 5L, 2L)

In [81]:
a.squeeze([1])

TypeError: an integer is required for the axis

In [86]:
a.squeeze([1,1,1])

TypeError: an integer is required for the axis

## Item selection and manipulation

In [88]:
a.shape

(3L, 5L, 2L)

In [92]:
a.nonzero()

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2], dtype=int64),
 array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 0, 0, 1,
        1, 2, 2, 3, 3, 4, 4], dtype=int64),
 array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
        1, 0, 1, 0, 1, 0, 1], dtype=int64))

In [93]:
a.argmax()

0

In [94]:
a = np.empty_like(a)

In [95]:
a.argmax()

1

In [96]:
a.argmin()

0

In [97]:
a.min()

0.0

In [98]:
a.max()

4.9406564584124654e-324

In [99]:
a.ptp

<function ptp>

In [100]:
a.ptp()

4.9406564584124654e-324

In [101]:
a.clip(a.min(), a.max())

array([[[  0.00000000e+000,   4.94065646e-324],
        [  0.00000000e+000,   4.94065646e-324],
        [  0.00000000e+000,   4.94065646e-324],
        [  0.00000000e+000,   4.94065646e-324],
        [  0.00000000e+000,   4.94065646e-324]],

       [[  0.00000000e+000,   4.94065646e-324],
        [  0.00000000e+000,   4.94065646e-324],
        [  0.00000000e+000,   4.94065646e-324],
        [  0.00000000e+000,   4.94065646e-324],
        [  0.00000000e+000,   4.94065646e-324]],

       [[  0.00000000e+000,   4.94065646e-324],
        [  0.00000000e+000,   4.94065646e-324],
        [  0.00000000e+000,   4.94065646e-324],
        [  0.00000000e+000,   4.94065646e-324],
        [  0.00000000e+000,   4.94065646e-324]]])